In [1]:
from __future__ import print_function
import torch

x = torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.2755e-39, 1.0837e-38, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 4.6838e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.2633, 0.5807, 0.0235],
        [0.4550, 0.0355, 0.6294],
        [0.7795, 0.1289, 0.3193],
        [0.3784, 0.9945, 0.6518],
        [0.9519, 0.3671, 0.2548]])


In [3]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### 데이터로부터 tensor를직접 생성하기

In [4]:
x = torch.tensor([5.5,3])
print(x)

x = x.new_ones(2,3,dtype=torch.double)
print(x)

x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1851, -0.9207,  0.8522],
        [-0.8585, -0.9947,  1.9137]])


#### 행렬의 크기 구하기

In [5]:
print(x.size())

torch.Size([2, 3])


#### 연산 - 예시로 덧셈에 사용되는 여러 가지 문법 살펴보기

In [6]:
x = torch.ones(5,3)
print(x)
y= torch.rand(5,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2760, 0.6949, 0.3497],
        [0.7338, 0.8631, 0.9887],
        [0.9715, 0.7115, 0.8026],
        [0.8507, 0.2912, 0.1248],
        [0.5117, 0.9690, 0.5066]])


#### 1

In [7]:
print(x+y)

tensor([[1.2760, 1.6949, 1.3497],
        [1.7338, 1.8631, 1.9887],
        [1.9715, 1.7115, 1.8026],
        [1.8507, 1.2912, 1.1248],
        [1.5117, 1.9690, 1.5066]])


#### 2

In [8]:
print(torch.add(x,y))

tensor([[1.2760, 1.6949, 1.3497],
        [1.7338, 1.8631, 1.9887],
        [1.9715, 1.7115, 1.8026],
        [1.8507, 1.2912, 1.1248],
        [1.5117, 1.9690, 1.5066]])


#### 3

In [9]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.2760, 1.6949, 1.3497],
        [1.7338, 1.8631, 1.9887],
        [1.9715, 1.7115, 1.8026],
        [1.8507, 1.2912, 1.1248],
        [1.5117, 1.9690, 1.5066]])


#### 4(In-place 방식)

In [10]:
y.add_(x)
print(y)

tensor([[1.2760, 1.6949, 1.3497],
        [1.7338, 1.8631, 1.9887],
        [1.9715, 1.7115, 1.8026],
        [1.8507, 1.2912, 1.1248],
        [1.5117, 1.9690, 1.5066]])


#### tensor의 size나 shape 변경

In [11]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1은 다른 차원들을 사용하여 유추한다.
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy 변환(Bridge)
#### CPU 상에서, Torch Tensor와 Numpy 배열은 저장공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다. 아래의 간단한 연산을 통해 확인한다.

#### Torch Tensor를 Numpy 배열로 변환하기

In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


###### **Tensor를 변경하면 Numpy 배열의 값도 자동 변경된다**

In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### Numpy 배열을 Torch Tensor로 변환하기

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


###### CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.